nodeLinker: node-modules

npmRegistries:
  //gitlab.sendpulse.com/api/v4/projects/169/packages/npm/:
    npmAlwaysAuth: true
    npmAuthToken: LiKxqyp5cTxnArYz7PUp
  //gitlab.sendpulse.com/api/v4/projects/227/packages/npm/:
    npmAlwaysAuth: true

npmScopes:
  sendpulse:
    npmPublishRegistry: "htts://gitlab.sendpulse.com/api/v4/projects/227/packages/npm/"
    npmRegistryServer: "https://gitlab.sendpulse.com/api/v4/projects/227/packages/npm/"
  sites:
    npmPublishRegistry: "https://gitlab.sendpulse.com/api/v4/projects/169/packages/npm/"
    npmRegistryServer: "https://gitlab.sendpulse.com/api/v4/projects/169/packages/npm/"

unsafeHttpWhitelist:
  - gitlab.sendpulse.com

yarnPath: .yarn/releases/yarn-4.0.2.cjs
